[build]
builder = "NIXPACKS"
buildCommand = """
  cargo install sqlx-cli --no-default-features --features postgres &&
  export DATABASE_URL=$DATABASE_URL &&
  cargo sqlx migrate run &&
  cargo build --release &&
  mkdir -p bin &&
  cp target/release/ddd_forum_api bin
  """

[deploy]
startCommand = "./bin/ddd_forum_api --port $PORT"
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 500
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
sleepApplication = true
region = "europe-west4"
